name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format Check
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets -- -D warnings
          cargo check --all-features
      - name: Test
        run:
          cargo test
      - name: MSRV
        run: |
          cargo install cargo-msrv@0.19.2
          cargo msrv verify
